序列图： webSocket正常收发


@startuml
actor User
participant App
participant AudioSdk as Sdk
participant AudioServer as Server

App -> Sdk: initSdk
App -> Sdk: setCookie

User -> App: pushToTalk
activate App
App -> Sdk: apiRealTimeRecord

activate Sdk
Sdk -> Sdk: beginRecord
Sdk -> Server: connectWebSocket
Server --> Sdk: connected

activate Sdk #Red
loop fetchAndSend while audio data not empty
Sdk -> Sdk: fetchAudioData
Sdk -> Server: sendData
    alt when success
    Server --> Sdk: textResult
    Sdk -> App: callback(text, SUCCESS)
    else when failed
    Server --> Sdk: errorMessage
    Sdk -> App: callback(errMsg, ERROR_SNIPPET)
    end
end

... RECORDING ...
User -> App: releaseEndTalk
App -> Sdk: apiStopRecord
deactivate App
Sdk -> Sdk: stopRecord

loop fetchAndSend while audio data not empty
Sdk -> Sdk: fetchAudioData
Sdk -> Server: sendData
    alt when success
    Server --> Sdk: textResult
    Sdk -> App: callback(text, SUCCESS)
    else when failed
    Server --> Sdk: errorMessage
    Sdk -> App: callback(errMsg, ERROR_SNIPPET)
    end
end
Sdk -> Server: closeWebSocket
Server --> Sdk: closed
Sdk -> App: callback("", FINISH)
deactivate Sdk
deactivate Sdk

@enduml